// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR-zf4NLGCpvCNdOX_B5BEAyZwNBgwEkQ',
    appId: '1:460340093561:web:9d33c3d014dd3de55eaaa8',
    messagingSenderId: '460340093561',
    projectId: 'reversefood-80720',
    authDomain: 'reversefood-80720.firebaseapp.com',
    storageBucket: 'reversefood-80720.firebasestorage.app',
    measurementId: 'G-TZPXBR5YKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Gz0UNZ_q-g5RKyAj9N3jce9w9vF0CqU',
    appId: '1:460340093561:android:4637418eab548e6c5eaaa8',
    messagingSenderId: '460340093561',
    projectId: 'reversefood-80720',
    storageBucket: 'reversefood-80720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3HVFwrB9dqOwd8w0XLvMj-ZmnSalsSwc',
    appId: '1:460340093561:ios:80a4a045f9aec5755eaaa8',
    messagingSenderId: '460340093561',
    projectId: 'reversefood-80720',
    storageBucket: 'reversefood-80720.firebasestorage.app',
    iosBundleId: 'com.example.grainchainfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3HVFwrB9dqOwd8w0XLvMj-ZmnSalsSwc',
    appId: '1:460340093561:ios:80a4a045f9aec5755eaaa8',
    messagingSenderId: '460340093561',
    projectId: 'reversefood-80720',
    storageBucket: 'reversefood-80720.firebasestorage.app',
    iosBundleId: 'com.example.grainchainfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR-zf4NLGCpvCNdOX_B5BEAyZwNBgwEkQ',
    appId: '1:460340093561:web:931c7e9459be29865eaaa8',
    messagingSenderId: '460340093561',
    projectId: 'reversefood-80720',
    authDomain: 'reversefood-80720.firebaseapp.com',
    storageBucket: 'reversefood-80720.firebasestorage.app',
    measurementId: 'G-WR675ENDSP',
  );
}
